/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Estructurapalabras;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EstructurapalabrasRecord extends UpdatableRecordImpl<EstructurapalabrasRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 593445874;

	/**
	 * Setter for <code>kutipak.estructurapalabras.TIPOID</code>.
	 */
	public void setTipoid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.estructurapalabras.TIPOID</code>.
	 */
	public Integer getTipoid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.estructurapalabras.ESTRUCTURAID</code>.
	 */
	public void setEstructuraid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.estructurapalabras.ESTRUCTURAID</code>.
	 */
	public Integer getEstructuraid() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Estructurapalabras.ESTRUCTURAPALABRAS.TIPOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Estructurapalabras.ESTRUCTURAPALABRAS.ESTRUCTURAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getTipoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getEstructuraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EstructurapalabrasRecord value1(Integer value) {
		setTipoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EstructurapalabrasRecord value2(Integer value) {
		setEstructuraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EstructurapalabrasRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EstructurapalabrasRecord
	 */
	public EstructurapalabrasRecord() {
		super(Estructurapalabras.ESTRUCTURAPALABRAS);
	}

	/**
	 * Create a detached, initialised EstructurapalabrasRecord
	 */
	public EstructurapalabrasRecord(Integer tipoid, Integer estructuraid) {
		super(Estructurapalabras.ESTRUCTURAPALABRAS);

		setValue(0, tipoid);
		setValue(1, estructuraid);
	}
}
