/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Idiomas;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IdiomasRecord extends UpdatableRecordImpl<IdiomasRecord> implements Record2<Integer, String> {

	private static final long serialVersionUID = -1840173100;

	/**
	 * Setter for <code>kutipak.idiomas.IDIOMAID</code>.
	 */
	public void setIdiomaid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.idiomas.IDIOMAID</code>.
	 */
	public Integer getIdiomaid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.idiomas.NOMBRE</code>.
	 */
	public void setNombre(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.idiomas.NOMBRE</code>.
	 */
	public String getNombre() {
		return (String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, String> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Idiomas.IDIOMAS.IDIOMAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Idiomas.IDIOMAS.NOMBRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdiomaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNombre();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdiomasRecord value1(Integer value) {
		setIdiomaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdiomasRecord value2(String value) {
		setNombre(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public IdiomasRecord values(Integer value1, String value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached IdiomasRecord
	 */
	public IdiomasRecord() {
		super(Idiomas.IDIOMAS);
	}

	/**
	 * Create a detached, initialised IdiomasRecord
	 */
	public IdiomasRecord(Integer idiomaid, String nombre) {
		super(Idiomas.IDIOMAS);

		setValue(0, idiomaid);
		setValue(1, nombre);
	}
}
