/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Palabras;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PalabrasRecord extends UpdatableRecordImpl<PalabrasRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, String, String> {

	private static final long serialVersionUID = 1822308782;

	/**
	 * Setter for <code>kutipak.palabras.PALABRAID</code>.
	 */
	public void setPalabraid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.PALABRAID</code>.
	 */
	public Integer getPalabraid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.palabras.IDIOMAID</code>.
	 */
	public void setIdiomaid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.IDIOMAID</code>.
	 */
	public Integer getIdiomaid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.palabras.TIPOID</code>.
	 */
	public void setTipoid(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.TIPOID</code>.
	 */
	public Integer getTipoid() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>kutipak.palabras.PAL_PALABRAID</code>.
	 */
	public void setPalPalabraid(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.PAL_PALABRAID</code>.
	 */
	public Integer getPalPalabraid() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>kutipak.palabras.TIEMPOSID</code>.
	 */
	public void setTiemposid(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.TIEMPOSID</code>.
	 */
	public Integer getTiemposid() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>kutipak.palabras.NOMBREPALABRA</code>.
	 */
	public void setNombrepalabra(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.NOMBREPALABRA</code>.
	 */
	public String getNombrepalabra() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>kutipak.palabras.SINONIMO</code>.
	 */
	public void setSinonimo(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>kutipak.palabras.SINONIMO</code>.
	 */
	public String getSinonimo() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, Integer, Integer, String, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Integer, Integer, Integer, Integer, String, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Palabras.PALABRAS.PALABRAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Palabras.PALABRAS.IDIOMAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Palabras.PALABRAS.TIPOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Palabras.PALABRAS.PAL_PALABRAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Palabras.PALABRAS.TIEMPOSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Palabras.PALABRAS.NOMBREPALABRA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return Palabras.PALABRAS.SINONIMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPalabraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getIdiomaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getTipoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getPalPalabraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getTiemposid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getNombrepalabra();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getSinonimo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value1(Integer value) {
		setPalabraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value2(Integer value) {
		setIdiomaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value3(Integer value) {
		setTipoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value4(Integer value) {
		setPalPalabraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value5(Integer value) {
		setTiemposid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value6(String value) {
		setNombrepalabra(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord value7(String value) {
		setSinonimo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PalabrasRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PalabrasRecord
	 */
	public PalabrasRecord() {
		super(Palabras.PALABRAS);
	}

	/**
	 * Create a detached, initialised PalabrasRecord
	 */
	public PalabrasRecord(Integer palabraid, Integer idiomaid, Integer tipoid, Integer palPalabraid, Integer tiemposid, String nombrepalabra, String sinonimo) {
		super(Palabras.PALABRAS);

		setValue(0, palabraid);
		setValue(1, idiomaid);
		setValue(2, tipoid);
		setValue(3, palPalabraid);
		setValue(4, tiemposid);
		setValue(5, nombrepalabra);
		setValue(6, sinonimo);
	}
}
