/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import persistencia.tables.Pantallapalabras;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PantallapalabrasRecord extends TableRecordImpl<PantallapalabrasRecord> implements Record6<Integer, String, String, String, String, String> {

	private static final long serialVersionUID = 1143822846;

	/**
	 * Setter for <code>kutipak.pantallapalabras.palabraid</code>.
	 */
	public void setPalabraid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.palabraid</code>.
	 */
	public Integer getPalabraid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.IDIOMA</code>.
	 */
	public void setIdioma(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.IDIOMA</code>.
	 */
	public String getIdioma() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.PALABRAS</code>.
	 */
	public void setPalabras(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.PALABRAS</code>.
	 */
	public String getPalabras() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.TRADUCCION</code>.
	 */
	public void setTraduccion(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.TRADUCCION</code>.
	 */
	public String getTraduccion() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.TIPO</code>.
	 */
	public void setTipo(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.TIPO</code>.
	 */
	public String getTipo() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>kutipak.pantallapalabras.TIEMPO</code>.
	 */
	public void setTiempo(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>kutipak.pantallapalabras.TIEMPO</code>.
	 */
	public String getTiempo() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Pantallapalabras.PANTALLAPALABRAS.PALABRAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Pantallapalabras.PANTALLAPALABRAS.IDIOMA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Pantallapalabras.PANTALLAPALABRAS.PALABRAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Pantallapalabras.PANTALLAPALABRAS.TRADUCCION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Pantallapalabras.PANTALLAPALABRAS.TIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Pantallapalabras.PANTALLAPALABRAS.TIEMPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPalabraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getIdioma();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPalabras();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTraduccion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getTipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTiempo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value1(Integer value) {
		setPalabraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value2(String value) {
		setIdioma(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value3(String value) {
		setPalabras(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value4(String value) {
		setTraduccion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value5(String value) {
		setTipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord value6(String value) {
		setTiempo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PantallapalabrasRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PantallapalabrasRecord
	 */
	public PantallapalabrasRecord() {
		super(Pantallapalabras.PANTALLAPALABRAS);
	}

	/**
	 * Create a detached, initialised PantallapalabrasRecord
	 */
	public PantallapalabrasRecord(Integer palabraid, String idioma, String palabras, String traduccion, String tipo, String tiempo) {
		super(Pantallapalabras.PANTALLAPALABRAS);

		setValue(0, palabraid);
		setValue(1, idioma);
		setValue(2, palabras);
		setValue(3, traduccion);
		setValue(4, tipo);
		setValue(5, tiempo);
	}
}
