/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Personas;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonasRecord extends UpdatableRecordImpl<PersonasRecord> implements Record6<Integer, String, String, String, String, String> {

	private static final long serialVersionUID = 131970854;

	/**
	 * Setter for <code>kutipak.personas.PERSONAID</code>.
	 */
	public void setPersonaid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.personas.PERSONAID</code>.
	 */
	public Integer getPersonaid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.personas.NOMBRES</code>.
	 */
	public void setNombres(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.personas.NOMBRES</code>.
	 */
	public String getNombres() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.personas.APELLIDOS</code>.
	 */
	public void setApellidos(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.personas.APELLIDOS</code>.
	 */
	public String getApellidos() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>kutipak.personas.CEDULA</code>.
	 */
	public void setCedula(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>kutipak.personas.CEDULA</code>.
	 */
	public String getCedula() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>kutipak.personas.CORREOELECTRONICO</code>.
	 */
	public void setCorreoelectronico(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>kutipak.personas.CORREOELECTRONICO</code>.
	 */
	public String getCorreoelectronico() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>kutipak.personas.TELEFONO</code>.
	 */
	public void setTelefono(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>kutipak.personas.TELEFONO</code>.
	 */
	public String getTelefono() {
		return (String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, String, String> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, String, String, String, String, String> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Personas.PERSONAS.PERSONAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return Personas.PERSONAS.NOMBRES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Personas.PERSONAS.APELLIDOS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Personas.PERSONAS.CEDULA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Personas.PERSONAS.CORREOELECTRONICO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return Personas.PERSONAS.TELEFONO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getPersonaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getNombres();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getApellidos();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getCedula();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getCorreoelectronico();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getTelefono();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord value1(Integer value) {
		setPersonaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord value2(String value) {
		setNombres(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord value3(String value) {
		setApellidos(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord value4(String value) {
		setCedula(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord value5(String value) {
		setCorreoelectronico(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord value6(String value) {
		setTelefono(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonasRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PersonasRecord
	 */
	public PersonasRecord() {
		super(Personas.PERSONAS);
	}

	/**
	 * Create a detached, initialised PersonasRecord
	 */
	public PersonasRecord(Integer personaid, String nombres, String apellidos, String cedula, String correoelectronico, String telefono) {
		super(Personas.PERSONAS);

		setValue(0, personaid);
		setValue(1, nombres);
		setValue(2, apellidos);
		setValue(3, cedula);
		setValue(4, correoelectronico);
		setValue(5, telefono);
	}
}
