/**
 * This class is generated by jOOQ
 */
package persistencia.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import persistencia.tables.Usuario;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsuarioRecord extends UpdatableRecordImpl<UsuarioRecord> implements Record5<Integer, Integer, String, String, Integer> {

	private static final long serialVersionUID = 1263499879;

	/**
	 * Setter for <code>kutipak.usuario.USUARIOID</code>.
	 */
	public void setUsuarioid(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>kutipak.usuario.USUARIOID</code>.
	 */
	public Integer getUsuarioid() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>kutipak.usuario.PERSONAID</code>.
	 */
	public void setPersonaid(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>kutipak.usuario.PERSONAID</code>.
	 */
	public Integer getPersonaid() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>kutipak.usuario.NOMBREUSUARIO</code>.
	 */
	public void setNombreusuario(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>kutipak.usuario.NOMBREUSUARIO</code>.
	 */
	public String getNombreusuario() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>kutipak.usuario.CONTRASENIA</code>.
	 */
	public void setContrasenia(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>kutipak.usuario.CONTRASENIA</code>.
	 */
	public String getContrasenia() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>kutipak.usuario.ROL</code>.
	 */
	public void setRol(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>kutipak.usuario.ROL</code>.
	 */
	public Integer getRol() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, String, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Usuario.USUARIO.USUARIOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Usuario.USUARIO.PERSONAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Usuario.USUARIO.NOMBREUSUARIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Usuario.USUARIO.CONTRASENIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return Usuario.USUARIO.ROL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getUsuarioid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getPersonaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getNombreusuario();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getContrasenia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getRol();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value1(Integer value) {
		setUsuarioid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value2(Integer value) {
		setPersonaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value3(String value) {
		setNombreusuario(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value4(String value) {
		setContrasenia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord value5(Integer value) {
		setRol(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UsuarioRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UsuarioRecord
	 */
	public UsuarioRecord() {
		super(Usuario.USUARIO);
	}

	/**
	 * Create a detached, initialised UsuarioRecord
	 */
	public UsuarioRecord(Integer usuarioid, Integer personaid, String nombreusuario, String contrasenia, Integer rol) {
		super(Usuario.USUARIO);

		setValue(0, usuarioid);
		setValue(1, personaid);
		setValue(2, nombreusuario);
		setValue(3, contrasenia);
		setValue(4, rol);
	}
}
