/**
 * This class is generated by jOOQ
 */
package persistencia.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import persistencia.Keys;
import persistencia.Kutipak;
import persistencia.tables.records.EstructurapalabrasRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Estructurapalabras extends TableImpl<EstructurapalabrasRecord> {

	private static final long serialVersionUID = 718160666;

	/**
	 * The reference instance of <code>kutipak.estructurapalabras</code>
	 */
	public static final Estructurapalabras ESTRUCTURAPALABRAS = new Estructurapalabras();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EstructurapalabrasRecord> getRecordType() {
		return EstructurapalabrasRecord.class;
	}

	/**
	 * The column <code>kutipak.estructurapalabras.TIPOID</code>.
	 */
	public final TableField<EstructurapalabrasRecord, Integer> TIPOID = createField("TIPOID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>kutipak.estructurapalabras.ESTRUCTURAID</code>.
	 */
	public final TableField<EstructurapalabrasRecord, Integer> ESTRUCTURAID = createField("ESTRUCTURAID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>kutipak.estructurapalabras</code> table reference
	 */
	public Estructurapalabras() {
		this("estructurapalabras", null);
	}

	/**
	 * Create an aliased <code>kutipak.estructurapalabras</code> table reference
	 */
	public Estructurapalabras(String alias) {
		this(alias, ESTRUCTURAPALABRAS);
	}

	private Estructurapalabras(String alias, Table<EstructurapalabrasRecord> aliased) {
		this(alias, aliased, null);
	}

	private Estructurapalabras(String alias, Table<EstructurapalabrasRecord> aliased, Field<?>[] parameters) {
		super(alias, Kutipak.KUTIPAK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EstructurapalabrasRecord> getPrimaryKey() {
		return Keys.KEY_ESTRUCTURAPALABRAS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EstructurapalabrasRecord>> getKeys() {
		return Arrays.<UniqueKey<EstructurapalabrasRecord>>asList(Keys.KEY_ESTRUCTURAPALABRAS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EstructurapalabrasRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EstructurapalabrasRecord, ?>>asList(Keys.FK_ESTRUCTURASTIPOS, Keys.FK_PALABRASESTRUCTURAS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Estructurapalabras as(String alias) {
		return new Estructurapalabras(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Estructurapalabras rename(String name) {
		return new Estructurapalabras(name, null);
	}
}
