/**
 * This class is generated by jOOQ
 */
package persistencia.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import persistencia.Keys;
import persistencia.Kutipak;
import persistencia.tables.records.EstructuraRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Estructura extends TableImpl<EstructuraRecord> {

	private static final long serialVersionUID = 929384772;

	/**
	 * The reference instance of <code>kutipak.estructura</code>
	 */
	public static final Estructura ESTRUCTURA = new Estructura();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EstructuraRecord> getRecordType() {
		return EstructuraRecord.class;
	}

	/**
	 * The column <code>kutipak.estructura.ESTRUCTURAID</code>.
	 */
	public final TableField<EstructuraRecord, Integer> ESTRUCTURAID = createField("ESTRUCTURAID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>kutipak.estructura.IDIOMAID</code>.
	 */
	public final TableField<EstructuraRecord, Integer> IDIOMAID = createField("IDIOMAID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>kutipak.estructura.NOMBREESTRUCTURA</code>.
	 */
	public final TableField<EstructuraRecord, String> NOMBREESTRUCTURA = createField("NOMBREESTRUCTURA", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>kutipak.estructura.FORMULA</code>.
	 */
	public final TableField<EstructuraRecord, String> FORMULA = createField("FORMULA", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>kutipak.estructura</code> table reference
	 */
	public Estructura() {
		this("estructura", null);
	}

	/**
	 * Create an aliased <code>kutipak.estructura</code> table reference
	 */
	public Estructura(String alias) {
		this(alias, ESTRUCTURA);
	}

	private Estructura(String alias, Table<EstructuraRecord> aliased) {
		this(alias, aliased, null);
	}

	private Estructura(String alias, Table<EstructuraRecord> aliased, Field<?>[] parameters) {
		super(alias, Kutipak.KUTIPAK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<EstructuraRecord, Integer> getIdentity() {
		return Keys.IDENTITY_ESTRUCTURA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EstructuraRecord> getPrimaryKey() {
		return Keys.KEY_ESTRUCTURA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EstructuraRecord>> getKeys() {
		return Arrays.<UniqueKey<EstructuraRecord>>asList(Keys.KEY_ESTRUCTURA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EstructuraRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EstructuraRecord, ?>>asList(Keys.FK_IDIOMA_ESTRUCTURA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Estructura as(String alias) {
		return new Estructura(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Estructura rename(String name) {
		return new Estructura(name, null);
	}
}
