/**
 * This class is generated by jOOQ
 */
package persistencia.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;

import persistencia.Kutipak;
import persistencia.tables.records.PantallapalabrasRecord;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pantallapalabras extends TableImpl<PantallapalabrasRecord> {

	private static final long serialVersionUID = 1541371930;

	/**
	 * The reference instance of <code>kutipak.pantallapalabras</code>
	 */
	public static final Pantallapalabras PANTALLAPALABRAS = new Pantallapalabras();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PantallapalabrasRecord> getRecordType() {
		return PantallapalabrasRecord.class;
	}

	/**
	 * The column <code>kutipak.pantallapalabras.palabraid</code>.
	 */
	public final TableField<PantallapalabrasRecord, Integer> PALABRAID = createField("palabraid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>kutipak.pantallapalabras.IDIOMA</code>.
	 */
	public final TableField<PantallapalabrasRecord, String> IDIOMA = createField("IDIOMA", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>kutipak.pantallapalabras.PALABRAS</code>.
	 */
	public final TableField<PantallapalabrasRecord, String> PALABRAS = createField("PALABRAS", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>kutipak.pantallapalabras.TRADUCCION</code>.
	 */
	public final TableField<PantallapalabrasRecord, String> TRADUCCION = createField("TRADUCCION", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>kutipak.pantallapalabras.TIPO</code>.
	 */
	public final TableField<PantallapalabrasRecord, String> TIPO = createField("TIPO", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>kutipak.pantallapalabras.TIEMPO</code>.
	 */
	public final TableField<PantallapalabrasRecord, String> TIEMPO = createField("TIEMPO", org.jooq.impl.SQLDataType.VARCHAR.length(5), this, "");

	/**
	 * Create a <code>kutipak.pantallapalabras</code> table reference
	 */
	public Pantallapalabras() {
		this("pantallapalabras", null);
	}

	/**
	 * Create an aliased <code>kutipak.pantallapalabras</code> table reference
	 */
	public Pantallapalabras(String alias) {
		this(alias, PANTALLAPALABRAS);
	}

	private Pantallapalabras(String alias, Table<PantallapalabrasRecord> aliased) {
		this(alias, aliased, null);
	}

	private Pantallapalabras(String alias, Table<PantallapalabrasRecord> aliased, Field<?>[] parameters) {
		super(alias, Kutipak.KUTIPAK, aliased, parameters, "VIEW");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Pantallapalabras as(String alias) {
		return new Pantallapalabras(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Pantallapalabras rename(String name) {
		return new Pantallapalabras(name, null);
	}
}
