/**
 * This class is generated by jOOQ
 */
package persistencia.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import persistencia.Keys;
import persistencia.Kutipak;
import persistencia.tables.records.PersonasRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Personas extends TableImpl<PersonasRecord> {

	private static final long serialVersionUID = -2016450543;

	/**
	 * The reference instance of <code>kutipak.personas</code>
	 */
	public static final Personas PERSONAS = new Personas();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PersonasRecord> getRecordType() {
		return PersonasRecord.class;
	}

	/**
	 * The column <code>kutipak.personas.PERSONAID</code>.
	 */
	public final TableField<PersonasRecord, Integer> PERSONAID = createField("PERSONAID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>kutipak.personas.NOMBRES</code>.
	 */
	public final TableField<PersonasRecord, String> NOMBRES = createField("NOMBRES", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>kutipak.personas.APELLIDOS</code>.
	 */
	public final TableField<PersonasRecord, String> APELLIDOS = createField("APELLIDOS", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>kutipak.personas.CEDULA</code>.
	 */
	public final TableField<PersonasRecord, String> CEDULA = createField("CEDULA", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>kutipak.personas.CORREOELECTRONICO</code>.
	 */
	public final TableField<PersonasRecord, String> CORREOELECTRONICO = createField("CORREOELECTRONICO", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>kutipak.personas.TELEFONO</code>.
	 */
	public final TableField<PersonasRecord, String> TELEFONO = createField("TELEFONO", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * Create a <code>kutipak.personas</code> table reference
	 */
	public Personas() {
		this("personas", null);
	}

	/**
	 * Create an aliased <code>kutipak.personas</code> table reference
	 */
	public Personas(String alias) {
		this(alias, PERSONAS);
	}

	private Personas(String alias, Table<PersonasRecord> aliased) {
		this(alias, aliased, null);
	}

	private Personas(String alias, Table<PersonasRecord> aliased, Field<?>[] parameters) {
		super(alias, Kutipak.KUTIPAK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<PersonasRecord, Integer> getIdentity() {
		return Keys.IDENTITY_PERSONAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PersonasRecord> getPrimaryKey() {
		return Keys.KEY_PERSONAS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PersonasRecord>> getKeys() {
		return Arrays.<UniqueKey<PersonasRecord>>asList(Keys.KEY_PERSONAS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Personas as(String alias) {
		return new Personas(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Personas rename(String name) {
		return new Personas(name, null);
	}
}
