/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Estructurapalabras implements Serializable {

	private static final long serialVersionUID = 372470411;

	private Integer tipoid;
	private Integer estructuraid;

	public Estructurapalabras() {}

	public Estructurapalabras(Estructurapalabras value) {
		this.tipoid = value.tipoid;
		this.estructuraid = value.estructuraid;
	}

	public Estructurapalabras(
		Integer tipoid,
		Integer estructuraid
	) {
		this.tipoid = tipoid;
		this.estructuraid = estructuraid;
	}

	public Integer getTipoid() {
		return this.tipoid;
	}

	public void setTipoid(Integer tipoid) {
		this.tipoid = tipoid;
	}

	public Integer getEstructuraid() {
		return this.estructuraid;
	}

	public void setEstructuraid(Integer estructuraid) {
		this.estructuraid = estructuraid;
	}
}
