/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Idiomas implements Serializable {

	private static final long serialVersionUID = 1873775093;

	private Integer idiomaid;
	private String  nombre;

	public Idiomas() {}

	public Idiomas(Idiomas value) {
		this.idiomaid = value.idiomaid;
		this.nombre = value.nombre;
	}

	public Idiomas(
		Integer idiomaid,
		String  nombre
	) {
		this.idiomaid = idiomaid;
		this.nombre = nombre;
	}

	public Integer getIdiomaid() {
		return this.idiomaid;
	}

	public void setIdiomaid(Integer idiomaid) {
		this.idiomaid = idiomaid;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}
