/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Palabras implements Serializable {

	private static final long serialVersionUID = -1258121944;

	private Integer palabraid;
	private Integer idiomaid;
	private Integer tipoid;
	private Integer palPalabraid;
	private Integer tiemposid;
	private String  nombrepalabra;
	private String  sinonimo;

	public Palabras() {}

	public Palabras(Palabras value) {
		this.palabraid = value.palabraid;
		this.idiomaid = value.idiomaid;
		this.tipoid = value.tipoid;
		this.palPalabraid = value.palPalabraid;
		this.tiemposid = value.tiemposid;
		this.nombrepalabra = value.nombrepalabra;
		this.sinonimo = value.sinonimo;
	}

	public Palabras(
		Integer palabraid,
		Integer idiomaid,
		Integer tipoid,
		Integer palPalabraid,
		Integer tiemposid,
		String  nombrepalabra,
		String  sinonimo
	) {
		this.palabraid = palabraid;
		this.idiomaid = idiomaid;
		this.tipoid = tipoid;
		this.palPalabraid = palPalabraid;
		this.tiemposid = tiemposid;
		this.nombrepalabra = nombrepalabra;
		this.sinonimo = sinonimo;
	}

	public Integer getPalabraid() {
		return this.palabraid;
	}

	public void setPalabraid(Integer palabraid) {
		this.palabraid = palabraid;
	}

	public Integer getIdiomaid() {
		return this.idiomaid;
	}

	public void setIdiomaid(Integer idiomaid) {
		this.idiomaid = idiomaid;
	}

	public Integer getTipoid() {
		return this.tipoid;
	}

	public void setTipoid(Integer tipoid) {
		this.tipoid = tipoid;
	}

	public Integer getPalPalabraid() {
		return this.palPalabraid;
	}

	public void setPalPalabraid(Integer palPalabraid) {
		this.palPalabraid = palPalabraid;
	}

	public Integer getTiemposid() {
		return this.tiemposid;
	}

	public void setTiemposid(Integer tiemposid) {
		this.tiemposid = tiemposid;
	}

	public String getNombrepalabra() {
		return this.nombrepalabra;
	}

	public void setNombrepalabra(String nombrepalabra) {
		this.nombrepalabra = nombrepalabra;
	}

	public String getSinonimo() {
		return this.sinonimo;
	}

	public void setSinonimo(String sinonimo) {
		this.sinonimo = sinonimo;
	}
}
