/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * VIEW
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pantallapalabras implements Serializable {

	private static final long serialVersionUID = 43598006;

	private Integer palabraid;
	private String  idioma;
	private String  palabras;
	private String  traduccion;
	private String  tipo;
	private String  tiempo;

	public Pantallapalabras() {}

	public Pantallapalabras(Pantallapalabras value) {
		this.palabraid = value.palabraid;
		this.idioma = value.idioma;
		this.palabras = value.palabras;
		this.traduccion = value.traduccion;
		this.tipo = value.tipo;
		this.tiempo = value.tiempo;
	}

	public Pantallapalabras(
		Integer palabraid,
		String  idioma,
		String  palabras,
		String  traduccion,
		String  tipo,
		String  tiempo
	) {
		this.palabraid = palabraid;
		this.idioma = idioma;
		this.palabras = palabras;
		this.traduccion = traduccion;
		this.tipo = tipo;
		this.tiempo = tiempo;
	}

	public Integer getPalabraid() {
		return this.palabraid;
	}

	public void setPalabraid(Integer palabraid) {
		this.palabraid = palabraid;
	}

	public String getIdioma() {
		return this.idioma;
	}

	public void setIdioma(String idioma) {
		this.idioma = idioma;
	}

	public String getPalabras() {
		return this.palabras;
	}

	public void setPalabras(String palabras) {
		this.palabras = palabras;
	}

	public String getTraduccion() {
		return this.traduccion;
	}

	public void setTraduccion(String traduccion) {
		this.traduccion = traduccion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTiempo() {
		return this.tiempo;
	}

	public void setTiempo(String tiempo) {
		this.tiempo = tiempo;
	}
}
