/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tiempos implements Serializable {

	private static final long serialVersionUID = -1133246082;

	private Integer tiemposid;
	private String  nombretiempo;

	public Tiempos() {}

	public Tiempos(Tiempos value) {
		this.tiemposid = value.tiemposid;
		this.nombretiempo = value.nombretiempo;
	}

	public Tiempos(
		Integer tiemposid,
		String  nombretiempo
	) {
		this.tiemposid = tiemposid;
		this.nombretiempo = nombretiempo;
	}

	public Integer getTiemposid() {
		return this.tiemposid;
	}

	public void setTiemposid(Integer tiemposid) {
		this.tiemposid = tiemposid;
	}

	public String getNombretiempo() {
		return this.nombretiempo;
	}

	public void setNombretiempo(String nombretiempo) {
		this.nombretiempo = nombretiempo;
	}
}
