/**
 * This class is generated by jOOQ
 */
package persistencia.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tipospalabras implements Serializable {

	private static final long serialVersionUID = -2126221009;

	private Integer tipoid;
	private String  nombretipo;
	private String  nemotecnico;

	public Tipospalabras() {}

	public Tipospalabras(Tipospalabras value) {
		this.tipoid = value.tipoid;
		this.nombretipo = value.nombretipo;
		this.nemotecnico = value.nemotecnico;
	}

	public Tipospalabras(
		Integer tipoid,
		String  nombretipo,
		String  nemotecnico
	) {
		this.tipoid = tipoid;
		this.nombretipo = nombretipo;
		this.nemotecnico = nemotecnico;
	}

	public Integer getTipoid() {
		return this.tipoid;
	}

	public void setTipoid(Integer tipoid) {
		this.tipoid = tipoid;
	}

	public String getNombretipo() {
		return this.nombretipo;
	}

	public void setNombretipo(String nombretipo) {
		this.nombretipo = nombretipo;
	}

	public String getNemotecnico() {
		return this.nemotecnico;
	}

	public void setNemotecnico(String nemotecnico) {
		this.nemotecnico = nemotecnico;
	}
}
